---
title: "p8105_fp_mjcr"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(httr)
library(rvest)
library(openintro)
library(ggmap)


```

Download data:

```{r, cache = TRUE, message = FALSE}
#cdc_df = GET("https://chronicdata.cdc.gov/resource/ta23-kdpu.csv") %>%
#  content("parsed") 

cdc_df = read_csv("./data/500_Cities__City-level_Data__GIS_Friendly_Format___2016_release.csv")

```

Select variables we may be interested in:

```{r}

cdc_df = cdc_df %>%
  select(c(StateAbbr, PlaceName, Population2010, ACCESS2_AdjPrev, BPHIGH_AdjPrev, BPMED_AdjPrev, CANCER_AdjPrev, CHD_AdjPrev, CHECKUP_AdjPrev, CHOLSCREEN_AdjPrev, COLON_SCREEN_AdjPrev, COPD_AdjPrev,COREM_AdjPrev, COREW_AdjPrev, DENTAL_AdjPrev, DIABETES_AdjPrev, HIGHCHOL_AdjPrev, LPA_AdjPrev, MAMMOUSE_AdjPrev, OBESITY_AdjPrev, PAPTEST_AdjPrev, PHLTH_AdjPrev, STROKE_AdjPrev, Geolocation)) %>% 
  mutate(state = abbr2state(StateAbbr)) %>%
  select(state, everything())

```

Merge data on state expenditure on healthcare:

```{r, message = FALSE}
#link: https://www.kff.org/other/state-indicator/health-spending-per-capita/?currentTimeframe=0&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D

#Importing the raw expenditure data set and cleaning
healthcare_exp_df = read_csv("./data/health_care_expenditure.csv", 
                             skip = 4, n_max = 51, col_names = F) %>%
  rename(state = "X1", health_exp = "X2") %>%
  mutate(health_exp = str_replace(health_exp, "\\$", ""),
         health_exp  = as.numeric(health_exp))


#Add state healthcare expenditure data to CDC data
cdc_df = left_join(cdc_df, healthcare_exp_df, by = "state")

cdc_df = cdc_df %>% mutate(state = abbr2state(StateAbbr))

```


Merge data regions per state:

```{r, message = FALSE}
regions_df = read_csv("https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv") %>%
  janitor::clean_names() %>%
  select(-state_code)
  

cdc_df = left_join(cdc_df, regions_df, by = "state")
```

Export merged data:

```{r}
write_csv(cdc_df, path = "./data/cdc_df.csv")
```


List of health practice variables and health outcome variables:

```{r}
health_practices = cdc_df %>%
  select(BPMED_AdjPrev, CHECKUP_AdjPrev, CHOLSCREEN_AdjPrev, COLON_SCREEN_AdjPrev, COREM_AdjPrev, COREW_AdjPrev, DENTAL_AdjPrev, LPA_AdjPrev, MAMMOUSE_AdjPrev, PAPTEST_AdjPrev)

health_outcomes = cdc_df %>%
  select(BPHIGH_AdjPrev, CANCER_AdjPrev, CHD_AdjPrev, COPD_AdjPrev, DIABETES_AdjPrev, HIGHCHOL_AdjPrev, OBESITY_AdjPrev, PHLTH_AdjPrev, STROKE_AdjPrev)

miscellaneous = cdc_df %>%
  select(StateAbbr, PlaceName, Population2010, ACCESS2_AdjPrev, Geolocation, state, health_exp, region, division)
```




Analyze some variables

```{r}

cdc_df %>%
  distinct(state, .keep_all = TRUE) %>%
  mutate(region = fct_reorder(region, health_exp)) %>%
  lm(health_exp ~ region, data = .) %>%
  summary

cdc_df %>%
  distinct(state, .keep_all = TRUE) %>%
  mutate(division = fct_reorder(division, health_exp)) %>%
  lm(health_exp ~ division, data = .) %>%
  summary


cdc_df %>%
  lm(health_exp ~ ACCESS2_AdjPrev, data = .) %>%
  summary


```


Map by expenditure:

```{r}

usa = map_data("state") %>%
  rename(state = "region")

cdc_df_map = cdc_df %>%
  separate(Geolocation, into = c("long", "lat"), sep = ",") %>%
  mutate(long = str_replace(long, "\\(", ""),
         lat = str_replace(lat, "\\)", ""),
         long = as.numeric(long),
         lat = as.numeric(lat),
         state = factor(state),
         state = tolower(state)) %>%
  filter(!state %in% c("alaska", "hawaii")) %>%
  left_join(., usa, by = "state")

ggplot() + 
  geom_polygon(data = cdc_df_map, aes(x = long.y, y = lat.y, group = state, fill = health_exp), color = "white") +
  coord_fixed(1) +
    geom_point(data = cdc_df_map, aes(x = lat.x, y = long.x), color = "grey15", size = 1) +
  theme_bw()


```



