---
title: "Team Registration and Proposal"
date: "November 7, 2018"
output: github_document
editor_options: 
  chunk_output_type: console
---

Team Members and UNIs:

Melanie Mayer; mm4963  
Jaisal Amin; ja3314  
Rebekah Yu; dry2115  
Courtney Johnson; cj2493  

Tentative Title:  
Exploring the Patterns of Adherence to Known Public Health Guidelines Across the United States and their Consequences  

The motivations for this project are to explore the impact of public health initiatives on health outcome, explore regional differences in health outcomes and the efficacy of public health initiatives, and explore if population size affects health.  

The intended final products are a clean data set with logically regionalized stratifications, a webpage with plots exploring the differences mentioned above, a report, and a screencast.  

The data we have chosen can be found at:  https://chronicdata.cdc.gov/500-Cities/500-Cities-City-level-Data-GIS-Friendly-Format-201/k56w-7tny   

Specifically, we plan on visualizing analysis of the associations between (1) prevalence of lack of health insurance, (2) regular health practices (i.e. pap smear, doctor visits, mammograms), and (3) health outcomes (diabetes, kidney disease, smoking). We also plan on  creating geographical visualizations of the prevalence of health outcomes by region.  

Some coding challenges we expect to run into are deciding how to define regions for the aformentioned analyses, using the selector gadget to create a data dictionary in a user friendly format (the site's data dictionary isn't its own file; it is listed on the webpage), determing which variables are the most important (there are 117 total), and tidying the data, as it is very large.  

Our planned timeline is as follows:  

November 12-16: have project meeting, and make changes to direction as discussed at the project review meeting.  

November 19-23: tidy data, determine region definitions, and determine important variables.  

November 26-30: Create webpage, conduct exploratory data analysis, conduct statistical analysis, and create plots.  

Dec 1-5: make screencast and report.  

December 6, 4 pm: submit report, webpage, and screencast.  

December 6, 8 pm: complete peer assessment.  

December 11: have in-class discussion of reports.